"""fixed student table relationship

Revision ID: 84447aa2037e
Revises: 85370c739b61
Create Date: 2026-09-01 04:30:40.700048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84447aa2037e'
down_revision = '85370c739b61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False))
        batch_op.create_index(batch_op.f('ix_student_gender'), ['gender'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_gender'))
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
