"""new tables

Revision ID: 85370c739b61
Revises: 
Create Date: 2026-09-01 04:12:49.157589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85370c739b61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_name'), ['name'], unique=True)

    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=25), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_course_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_name'), ['name'], unique=True)

    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_name'), ['name'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'ADMIN', 'SUPER_ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_password_hash'), ['password_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_year'), ['year'], unique=False)

    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_filename'), ['filename'], unique=True)
        batch_op.create_index(batch_op.f('ix_file_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_uploaded_at'), ['uploaded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_uploaded_by'), ['uploaded_by'], unique=False)

    op.create_table('invitation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('invited_by_id', sa.Integer(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('role', sa.Enum('STUDENT', 'ADMIN', 'SUPER_ADMIN', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invitation_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitation_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_invitation_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitation_invited_by_id'), ['invited_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitation_is_used'), ['is_used'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitation_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitation_username'), ['username'], unique=True)

    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_start_time'), ['start_time'], unique=False)

    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'ADMIN', 'SUPER_ADMIN', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_student_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('ix_student_year'), ['year'], unique=False)

    op.create_table('download_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('downloaded_by', sa.Integer(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['downloaded_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('download_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_download_log_downloaded_at'), ['downloaded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_download_log_downloaded_by'), ['downloaded_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_download_log_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_download_log_id'), ['id'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('Target_role', sa.String(length=50), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_posted_at'), ['posted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_schedule_id'), ['schedule_id'], unique=False)

    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('reported_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RESOLVED', 'DISMISSES', name='reportstatus'), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_by'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'reported_by', name='uq_file_reporter')
    )
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_reported_by'), ['reported_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_resolved_at'), ['resolved_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_status'))
        batch_op.drop_index(batch_op.f('ix_report_resolved_at'))
        batch_op.drop_index(batch_op.f('ix_report_reported_by'))
        batch_op.drop_index(batch_op.f('ix_report_id'))
        batch_op.drop_index(batch_op.f('ix_report_file_id'))

    op.drop_table('report')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_schedule_id'))
        batch_op.drop_index(batch_op.f('ix_notification_posted_at'))
        batch_op.drop_index(batch_op.f('ix_notification_id'))
        batch_op.drop_index(batch_op.f('ix_notification_file_id'))
        batch_op.drop_index(batch_op.f('ix_notification_created_by_id'))

    op.drop_table('notification')
    with op.batch_alter_table('download_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_download_log_id'))
        batch_op.drop_index(batch_op.f('ix_download_log_file_id'))
        batch_op.drop_index(batch_op.f('ix_download_log_downloaded_by'))
        batch_op.drop_index(batch_op.f('ix_download_log_downloaded_at'))

    op.drop_table('download_log')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_year'))
        batch_op.drop_index(batch_op.f('ix_student_username'))
        batch_op.drop_index(batch_op.f('ix_student_role'))
        batch_op.drop_index(batch_op.f('ix_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_email'))
        batch_op.drop_index(batch_op.f('ix_student_created_at'))

    op.drop_table('student')
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_start_time'))
        batch_op.drop_index(batch_op.f('ix_schedule_id'))
        batch_op.drop_index(batch_op.f('ix_schedule_end_time'))
        batch_op.drop_index(batch_op.f('ix_schedule_created_by_id'))

    op.drop_table('schedule')
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invitation_username'))
        batch_op.drop_index(batch_op.f('ix_invitation_role'))
        batch_op.drop_index(batch_op.f('ix_invitation_is_used'))
        batch_op.drop_index(batch_op.f('ix_invitation_invited_by_id'))
        batch_op.drop_index(batch_op.f('ix_invitation_id'))
        batch_op.drop_index(batch_op.f('ix_invitation_email'))
        batch_op.drop_index(batch_op.f('ix_invitation_created_at'))

    op.drop_table('invitation')
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_uploaded_by'))
        batch_op.drop_index(batch_op.f('ix_file_uploaded_at'))
        batch_op.drop_index(batch_op.f('ix_file_id'))
        batch_op.drop_index(batch_op.f('ix_file_filename'))
        batch_op.drop_index(batch_op.f('ix_file_course_id'))
        batch_op.drop_index(batch_op.f('ix_file_category_id'))

    op.drop_table('file')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_year'))
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.drop_index(batch_op.f('ix_user_password_hash'))
        batch_op.drop_index(batch_op.f('ix_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_created_at'))

    op.drop_table('user')
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_name'))
        batch_op.drop_index(batch_op.f('ix_group_id'))
        batch_op.drop_index(batch_op.f('ix_group_created_at'))

    op.drop_table('group')
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_name'))
        batch_op.drop_index(batch_op.f('ix_course_id'))
        batch_op.drop_index(batch_op.f('ix_course_code'))

    op.drop_table('course')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_name'))
        batch_op.drop_index(batch_op.f('ix_category_id'))

    op.drop_table('category')
    # ### end Alembic commands ###
