"""added new tables

Revision ID: c536cf1f621e
Revises: ff323054ea66
Create Date: 2026-08-03 20:28:33.023724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c536cf1f621e'
down_revision = 'ff323054ea66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_start_time'), ['start_time'], unique=False)

    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.alter_column('invited_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'user', ['invited_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('invited_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_start_time'))
        batch_op.drop_index(batch_op.f('ix_schedule_id'))
        batch_op.drop_index(batch_op.f('ix_schedule_end_time'))
        batch_op.drop_index(batch_op.f('ix_schedule_created_by_id'))

    op.drop_table('schedule')
    # ### end Alembic commands ###
